server:
    port: 8080
    servlet:
        context-path: /api/v1
spring:
    main:
        allow-bean-definition-overriding: true
    cache:
        type: redis
        host: localhost
        port: 6379
        redis:
            time-to-live: 60000  #data will be cleared from the cache after every minute.
    application:
        name: book-backend
    r2dbc:
        url: ${URL:r2dbc:postgresql://localhost:5432/books_db}
        username: ${USERNAME:postgres}
        password: ${PASSWORD:1234}
    data:
        r2dbc:
            repositories:
                enabled: true
    graphql:
        graphiql:
          enabled: true
        path: /graphql

logging:
    level:
      org:
          springframework:
              r2dbc=DEBUG:
#management:
#    properties:
#        jmxremote:
#            local:
#                only: false
